# Generated by Django 2.2.4 on 2024-04-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
